<?php

/**
 * Implements hook_uninstall().
 */
function bellcom_borgerdk_uninstall() {
  //getting the variables
  module_load_include('module', 'bellcom_borgerdk', 'bellcom_borgerdk');

  drupal_uninstall_schema('bellcom_borgerdk');

  $queue = DrupalQueue::get(BELLCOM_BORGERDK_QUEUE);
  $queue->deleteQueue();
}

/**
 * Implements hook_schema().
 */
function bellcom_borgerdk_schema() {
  $schema = array();

  $schema['borgerdk_article'] = array(
    'description' => 'Keeps the information about Borger.dk articles.',
    'fields' => array(
      'entity_id' => array(
        'description' => 'Primary key and id, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
      'title' => array(
        'description' => 'A title for the item, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'header' => array(
        'description' => 'A header for the item, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
      ),
      'articleUrl' => array(
        'description' => 'The URL of the article, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
      ),
      'legislation' => array(
        'description' => 'Legislation section of article, taken from Borger.dk',
        'type' => 'text',
        'size' => 'big',
      ),
      'recommendation' => array(
        'description' => 'Recommendation section of article, taken from Borger.dk',
        'type' => 'text',
        'size' => 'big',
      ),
      'byline' => array(
        'description' => 'The byline of the article, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 255,
      ),
      'lastUpdated' => array(
        'description' => 'The Unix timestamp of the entity last updated date, taken from Borger.dk',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'publishingDate' => array(
        'description' => 'The Unix timestamp of the entity publishing date, taken from Borger.dk',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'resynch' => array(
        'description' => 'The flag indicating that this article is behind its version from Borger.dk',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
      ),
      'uid' => array(
        'description' => 'Author uid of this article, 0 if imported automatically',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'changed' => array(
        'description' => 'The Unix timestamp of the entity changed time.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'created' => array(
        'description' => 'The Unix timestamp of the entity created time.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'lang' => array(
        'description' => 'Language field, indicated whether the entity is from Danish or English version of Borger.dk',
        'type' => 'char',
        'length' => 2,
        'not null' => TRUE,
        'default' => 'da'
      )
    ),
    'primary key' => array('entity_id'),
  );

  $schema['borgerdk_microarticle'] = array(
    'description' => 'Keeps the information about Borger.dk mircoarticles.',
    'fields' => array(
      'entity_id' => array(
        'description' => 'Primary key and id, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
      'vid' => array(
        'description' => 'The ID of the entity\'s default revision.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => NULL,
      ),
      'title' => array(
        'description' => 'A title for the microarticle, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'content' => array(
        'description' => 'Content of the microarticle, taken from Borger.dk',
        'type' => 'text',
        'size' => 'big',
      ),
      'weight' => array(
        'description' => 'The order of the self-service, taken from Borger.dk',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'article_id' => array(
        'description' => 'Foreign key to borgerdk_article entity_id',
        'type' => 'varchar',
        'length' => 50,
      ),
      'uid' => array(
        'description' => 'Author uid of this microarticle, 0 if imported automatically',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'changed' => array(
        'description' => 'The Unix timestamp of the entity changed time.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'created' => array(
        'description' => 'The Unix timestamp of the entity created time.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('entity_id'),
  );

  $schema['borgerdk_microarticle_revision'] = $schema['borgerdk_microarticle'];
  $schema['borgerdk_microarticle_revision']['fields']['vid'] = array(
    'description' => 'The primary identifier.',
    'type' => 'serial',
    'not null' => TRUE,
  );
  $schema['borgerdk_microarticle_revision']['fields']['entity_id'] = array(
    'description' => 'The ID of the attached entity.',
    'type' => 'varchar',
    'length' => 50,
    'not null' => FALSE,
    'default' => NULL,
  );
  $schema['borgerdk_microarticle_revision']['primary key'] = array('vid');


  $schema['borgerdk_selfservice'] = array(
    'description' => 'Keeps the information about Borger.dk self-service links.',
    'fields' => array(
      'entity_id' => array(
        'description' => 'Primary key and id, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
      'vid' => array(
        'description' => 'The ID of the entity\'s default revision.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => NULL,
      ),
      'title' => array(
        'description' => 'A title (href title attribute) for the self-service, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'label' => array(
        'description' => 'A label for the self-service, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'url' => array(
        'description' => 'The URL of the self-service, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'weight' => array(
        'description' => 'The order of the self-service, taken from Borger.dk',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'article_id' => array(
        'description' => 'Foreign key to borgerdk_article entity_id',
        'type' => 'varchar',
        'length' => 50,
      ),
      'microarticle_id' => array(
        'description' => 'Foreign key to borgerdk_microarticle entity_id',
        'type' => 'varchar',
        'length' => 50,
      ),
      'uid' => array(
        'description' => 'Author uid of this self-service, 0 if imported automatically',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'changed' => array(
        'description' => 'The Unix timestamp of the entity changed time.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'created' => array(
        'description' => 'The Unix timestamp of the entity created time.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('entity_id'),
  );

  $schema['borgerdk_selfservice_revision'] = $schema['borgerdk_selfservice'];
  $schema['borgerdk_selfservice_revision']['fields']['vid'] = array(
    'description' => 'The primary identifier.',
    'type' => 'serial',
    'not null' => TRUE,
  );
  $schema['borgerdk_selfservice_revision']['fields']['entity_id'] = array(
    'description' => 'The ID of the attached entity.',
    'type' => 'varchar',
    'length' => 50,
    'not null' => FALSE,
    'default' => NULL,
  );
  $schema['borgerdk_selfservice_revision']['primary key'] = array('vid');

  return $schema;
}

/**
 * Implements hook_field_schema().
 */
function bellcom_borgerdk_field_schema($field) {
  return array(
    'columns' => array(
      'borgerdk_article_entity_id' => array(
        'description' => 'Primary key and id, taken from Borger.dk',
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
      'borgerdk_microarticle_entity_ids' => array(
        'type' => 'text',
        'size' => 'normal'
      ),
      'borgerdk_selfservice_entity_ids' => array(
        'type' => 'text',
        'size' => 'normal'
      ),
    ),
  );
}

/**
 * Updates the field borgerdk_article_entity_id to nullable.
 *
 */
function bellcom_borgerdk_update_7101() {
  //updating existing field types
  $fields = field_info_fields();
  foreach ($fields as $field_name => $field) {
    if ($field['type'] == 'borgerdk_article_field' && $field['storage']['type'] == 'field_sql_storage') {
      foreach ($field['storage']['details']['sql'] as $type => $table_info) {
        foreach ($table_info as $table_name => $columns) {
          $column_name = _field_sql_storage_columnname($field_name, 'borgerdk_article_entity_id');
          db_change_field($table_name, $column_name, $column_name, array(
            'type' => 'int',
          ));
        }
      }
    }
  }
}

/**
 * Updates the borger.dk structure to have the lang prefix in article entity ids.
 *
 */
function bellcom_borgerdk_update_7102() {
  //adding new lang field
  db_add_field('borgerdk_article', 'lang', array(
    'description' => 'Language field, indicated whether the entity is from Danish or English version of Borger.dk',
    'type' => 'char',
    'length' => 2,
    'not null' => TRUE,
    'default' => 'da'
  ));

  //changing field's type to varchar
  db_change_field('borgerdk_article', 'entity_id', 'entity_id', array(
    'description' => 'Primary key and id, taken from Borger.dk',
    'type' => 'varchar',
    'length' => 50,
    'not null' => TRUE,
  ));
  db_change_field('borgerdk_microarticle', 'article_id', 'article_id', array(
    'description' => 'Foreign key to borgerdk_article entity_id',
    'type' => 'varchar',
    'length' => 50,
  ));
  db_change_field('borgerdk_microarticle_revision', 'article_id', 'article_id', array(
    'description' => 'Foreign key to borgerdk_article entity_id',
    'type' => 'varchar',
    'length' => 50,
  ));
  db_change_field('borgerdk_selfservice', 'article_id', 'article_id', array(
    'description' => 'Foreign key to borgerdk_article entity_id',
    'type' => 'varchar',
    'length' => 50,
  ));
  db_change_field('borgerdk_selfservice_revision', 'article_id', 'article_id', array(
    'description' => 'Foreign key to borgerdk_article entity_id',
    'type' => 'varchar',
    'length' => 50,
  ));

  //adding lang suffix to existing articles, it's safe to assume that all existing articles are Danish
  db_query("UPDATE {borgerdk_article} SET entity_id = CONCAT(entity_id, '-da')");
  db_query("UPDATE {borgerdk_microarticle} SET article_id = CONCAT(article_id, '-da')");
  db_query("UPDATE {borgerdk_microarticle_revision} SET article_id = CONCAT(article_id, '-da')");
  db_query("UPDATE {borgerdk_selfservice} SET article_id = CONCAT(article_id, '-da')");
  db_query("UPDATE {borgerdk_selfservice_revision} SET article_id = CONCAT(article_id, '-da')");

  //updating existing field types
  $fields = field_info_fields();
  foreach ($fields as $field_name => $field) {
    if ($field['type'] == 'borgerdk_article_field' && $field['storage']['type'] == 'field_sql_storage') {
      foreach ($field['storage']['details']['sql'] as $type => $table_info) {
        foreach ($table_info as $table_name => $columns) {
          $column_name = _field_sql_storage_columnname($field_name, 'borgerdk_article_entity_id');
          db_change_field($table_name, $column_name, $column_name, array(
            'description' => 'Primary key and id, taken from Borger.dk',
            'type' => 'varchar',
            'length' => 50,
            'not null' => TRUE,
          ));
        }
      }
    }
  }

  //updating all article reference fields
  $fields = field_read_fields(array('type' => 'borgerdk_article_field'));
  foreach ($fields as $field) {
    $field_instances = field_read_instances(array('field_id' => $field['id']));
    foreach ($field_instances as $field_instance) {
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', $field_instance['entity_type'])
        ->entityCondition('bundle', $field_instance['bundle'])
        ->fieldCondition($field_instance['field_name'], 'borgerdk_article_entity_id', 'NULL', '!=');

      $result = $query->execute();
      if (isset($result['node'])) {
        $nids = array_keys($result['node']);
        $nodes = entity_load('node', $nids);

        foreach ($nodes as $node) {
          foreach ($node->{$field_instance['field_name']}['und'] as $delta => $node_field) {
            $node->{$field_instance['field_name']}['und'][$delta]['borgerdk_article_entity_id'] = $node_field['borgerdk_article_entity_id'] . '-da';
          }
          node_save($node);
        }
      }
    }
  }
}

/**
 * Increase header field length.
 *
 */
function bellcom_borgerdk_update_7103() {
 //changing field's type to varchar
  db_change_field('borgerdk_article', 'header', 'header', array(
    'description' => 'A header for the item, taken from Borger.dk',
    'type' => 'varchar',
    'length' => 500,
    'not null' => FALSE,
    'default' => '',
  ));
}
