<?php
define('BELLCOM_BORGERDK_QUEUE', 'bellcom_borgerdk_cron_queue');
define('BELLCOM_BORGERDK_QUEUE_CHUNK_SIZE', 10); //used when scheduling items to be imported
define('BELLCOM_BORGERDK_CONTROLLER_UI_PAGER_LIMIT', 25); //used when presenting items in admin overview

module_load_include('inc', 'bellcom_borgerdk', 'entities/bellcom_borgerdk_article.entity');
module_load_include('inc', 'bellcom_borgerdk', 'entities/bellcom_borgerdk_microarticle.entity');
module_load_include('inc', 'bellcom_borgerdk', 'entities/bellcom_borgerdk_selfservice.entity');
module_load_include('inc', 'bellcom_borgerdk', 'includes/bellcom_borgerdk.fields');
module_load_include('inc', 'bellcom_borgerdk', 'includes/bellcom_borgerdk.synch');
module_load_include('inc', 'bellcom_borgerdk', 'admin/bellcom_borgerdk.article.admin');
module_load_include('inc', 'bellcom_borgerdk', 'admin/bellcom_borgerdk.microarticle.admin');
module_load_include('inc', 'bellcom_borgerdk', 'admin/bellcom_borgerdk.selfservice.admin');

/**
 * Implements hook_menu()
 */
function bellcom_borgerdk_menu() {
  $items = array();

  $items += bellcom_borgedk_article_menu();
  $items += bellcom_borgerdk_microarticle_menu();
  $items += bellcom_borgerdk_selfservice_menu();

  return $items;
}

/**
 * Implements hook_cron()
 *
 * fetches the latest info about articles.
 * Add the articles that need to be resynched to the dedicated queue.
 */
function bellcom_borgerdk_cron() {
  $queue = DrupalQueue::get(BELLCOM_BORGERDK_QUEUE);

  if ($queue_size = $queue->numberOfItems()) {
    watchdog('Bellcom Borger.dk', 'Borger.dk article queue is not empty (about @cnt articles pending update), new items will not be created.',
      array('@cnt' => $queue_size * BELLCOM_BORGERDK_QUEUE_CHUNK_SIZE));
  }
  else {
    try {
      bellcom_borgerdk_fetch_articles();
      $articles = bellcom_borgedk_get_resynch_articles();

      // Maximum N articles to process.
      $chunks = array_chunk($articles, BELLCOM_BORGERDK_QUEUE_CHUNK_SIZE, TRUE);
      foreach ($chunks as $chunk) {
        $queue->createItem($chunk);
      }
      watchdog('Bellcom Borger.dk', 'Borger article queue created (@cnt articles pending update).',
        array('@cnt' => count($articles)));
    } catch (Exception $e) {
      watchdog('Bellcom Borger.dk', $e->getMessage(), WATCHDOG_ERROR);
    }
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function bellcom_borgerdk_cron_queue_info() {
  $queues[BELLCOM_BORGERDK_QUEUE] = array(
    'worker callback' => 'bellcom_borgerdk_queue_worker',
    'time' => 60,
  );
  return $queues;
}

/**
 * Implements hook_entity_info().
 */
function bellcom_borgerdk_entity_info() {
  $info = array();

  $info += bellcom_borgedk_article_entity_info();
  $info += bellcom_borgedk_microarticle_entity_info();
  $info += bellcom_borgerdk_selfservice_entity_info();

  return $info;
}

/**
 * Implements hook_permission().
 */
function bellcom_borgerdk_permission() {
  $permissions = array(
    'administer borgerdk_article' => array(
      'title' => t('Administer Borger.dk Articles'),
      'description' => t('Edit and view all Borger.dk Articles.'),
    ),
    'view borgerdk_article' => array(
      'title' => t('View Borger.dk Articles'),
      'description' => t('View all Borger.dk Articles.'),
    ),
    'create borgerdk_article' => array(
      'title' => t('Create Borger.dk Articles'),
      'description' => t('Create all Borger.dk Articles.'),
    ),
    'update borgerdk_article' => array(
      'title' => t('Edit all Borger.dk Articles'),
      'description' => t('Edit all Borger.dk Articles.'),
    ),
    'delete borgerdk_article' => array(
      'title' => t('Delete Borger.dk Articles'),
      'description' => t('Delete all Borger.dk Articles.'),
    ),
  );

  return $permissions;
}